name: Org Actions Test

# TODO: find out how to limit push action to main.
on: [push, pull_request]

permissions:
  contents: read

jobs:
  stuff:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # This is required for requesting the OIDC JWT
    name: Node 20
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: "20"
      - uses: actions/checkout@v3
      - id: get_creds

        uses: samarthgowda96/test-my-action/image-create@main

        with:
          re_environment: "dev"
          # debug: true
      # - run: >
      # curl -i "https://config.dev-radioedit.ihrint.com/graphql"
      # -H "Authorization: Bearer #
      # -H "Content-Type: application/json"
      #--data '{"query": "{application(appId:\"helloworld\"){name}}"}'
